name: Deploy to Production

on:
  push:
    branches: [main]
    paths:
      - 'Frontend/**'
      - 'Server/**'
      - 'Python-microservice/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Rebuild PEM from single-line secret
      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: ssh-keyscan -H 82.177.167.151 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@82.177.167.151 '
            set -e
            cd ECHONET &&
            git fetch origin &&
            git reset --hard origin/main &&
            sudo docker compose down &&
            sudo docker compose up --build -d --force-recreate
          '

      - name: Verify deployment
        run: ssh ubuntu@82.177.167.151 'sudo docker compose ps'
