name: Deploy to Production

on:
  push:
    branches: [main]
    paths:
      - 'Frontend/**'
      - 'Server/**'  # Assuming Server is your Backend
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan -H 82.177.167.151 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ubuntu@82.177.167.151 '
            set -e
            cd ECHONET &&
            git fetch origin &&
            git reset --hard origin/main &&
            sudo docker compose down &&
            sudo docker compose up --build -d --force-recreate
          '

      - name: Verify deployment
        run: |
          ssh ubuntu@82.177.167.151 '
            sudo docker compose ps
          '

      - name: Cleanup SSH key
        if: always()
        run: |
          # The ssh-agent action handles cleanup, but if you had manual keys:
          # rm -f ~/.ssh/cloud_rsa
          echo "SSH key cleanup is handled by ssh-agent action."